version: '3.8'
services:
  stampcollection:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stampcollection
    volumes:
      - ./:/app
    depends_on:
      - db
    command: ./mvnw spring-boot:run

  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=stamp
      - POSTGRES_USER=stamp
      - POSTGRES_DB=stampcollection